version: 2
jobs:
  build:
    working_directory: ~/ogp
    machine: true
    steps:
      - checkout
      - run:
          name: "docker version"
          command: |
            docker -v
      - run:
          name: "Build Image"
          command: |
            make build
